#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/bgaujac/wwae/swwae

#$ -l gpu=True
#$ -l tmem=24G
#$ -l h_rt=9:00:00

#$ -t 1-1

#$ -N detswsvhn

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-10.0.source

python3 array_run.py --num_it 150000 --data_dir ../../data --dataset svhn --out_dir svhn_autoencod --model WAE --lr 0.001 --beta 0 --slicing_dist det --save_model --cost sw
